name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate
        uses: seeebiii/redoc-cli-github-action@v10
        with:
          args: 'bundle specification.yaml -o index.html'

  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .
          force_orphan: true
