name: Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate
        uses: seeebiii/redoc-cli-github-action@v10
        with:
          args: 'bundle specification.yaml'
